package com.example.miniproyecto2pruebas.controller;

import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.event.ActionEvent;
import java.io.IOException;

/**
 * The {@code HomeController} class is the controller for the home screen of the game.
 * It handles user interactions with the home screen, including displaying the logo and
 * navigating to the Sudoku game stage when the "Play" button is clicked.
 * This class follows the Model-View-Controller (MVC) architecture, where the controller
 * manages the logic and user input, delegating the interaction with the view and model.
 *
 * @author David Taborda and Juan Pablo Piedrahita.
 * @version 3.0
 * @since 2.0
 */
public class HomeController {
    /**
     * The {@link ImageView} that displays the logo on the home screen.
     * This is annotated with {@code @FXML} to link it with the corresponding
     * element in the FXML file.
     */
    @FXML
    private ImageView logoImage;

    /**
     * The {@link Button} that starts the game when clicked.
     * This is annotated with {@code @FXML} to link it with the corresponding
     * element in the FXML file.
     */
    @FXML
    private Button playButton;

    /**
     * Initializes the home screen by loading the logo image and setting it in the {@link ImageView}.
     * This method is called automatically by JavaFX when the FXML file is loaded.
     *
     * @see javafx.fxml.FXML
     */
    @FXML
    public void initialize() {
        Image logo = new Image(String.valueOf(getClass().getResource("/com/example/miniproyecto2pruebas/logo.png")));
        logoImage.setImage(logo);
    }

    /**
     * Handles the "Play" button click event.
     * It creates an instance of {@link ButtonActionAdapter.PlayButtonAction} and
     * calls its {@link IButtonAction#execute(ActionEvent)} method to transition
     * to the Sudoku game stage and close the home stage.
     *
     * @param event the event generated by the "Play" button click.
     * @throws IOException if there is an issue during the transition to the Sudoku stage.
     * @see IButtonAction
     * @see ButtonActionAdapter.PlayButtonAction
     */
    @FXML
    public void handlePlayButton(ActionEvent event) throws IOException {
        IButtonAction action = new ButtonActionAdapter.PlayButtonAction();
        action.execute(event);
    }
}