package com.example.miniproyecto2pruebas.controller;

import javafx.event.ActionEvent;
import java.io.IOException;

/**
 * The {@code IButtonAction} interface defines the contract for actions associated with button clicks in the application.
 * Classes implementing this interface must define the {@code execute} method, which contains the logic to be executed
 * when a button is clicked.
 *
 * This interface is part of the Model-View-Controller (MVC) architecture and allows for flexible handling of user
 * interactions with buttons in the view. Each controller that implements this interface can define its own behavior
 * for specific button actions.
 *
 * @author Juan Pablo Piedrahita.
 * @version 3.0
 * @since 2.0
 */
public interface IButtonAction {
    /**
     * Executes the action associated with a button click.
     * This method is called when a button is clicked, and it should contain the logic to handle the button's action.
     *
     * @param event the event generated by the button click, providing details such as the source of the event.
     * @throws IOException if there is an issue during the execution of the button's action (e.g., loading resources).
     */
    void execute(ActionEvent event) throws IOException;
}
